#!/bin/sh
export AUTH0_DOMAIN="AUTH0 DOMAIN"
export ALGORITHMS="ALGORITHMS"
export API_AUDIENCE="api audience"
export DATABASE_URL=""
export DATABASE_USER="user"
export DATABASE_PASSWORD="password"
export FLASK_APP="app.py"
export ASSISTANT_TOKEN=""
export PRODUCER_TOKEN=""